#!/bin/bash
# DisasterWatch - Complete Startup Guide

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}======================================${NC}"
echo -e "${BLUE}  DisasterWatch - Startup Guide${NC}"
echo -e "${BLUE}======================================${NC}"
echo ""

echo -e "${YELLOW}You need to open 3 separate terminals/PowerShell windows:${NC}"
echo ""

echo -e "${GREEN}TERMINAL 1: Backend (Django API)${NC}"
echo "Location: backend/"
echo "Command:"
echo "  cd backend"
echo "  python manage.py runserver"
echo ""
echo "Expected Output:"
echo "  Django version 5.x.x, using settings 'disasterwatch_backend.settings'"
echo "  Starting development server at http://127.0.0.1:8000/"
echo ""
echo "✓ Backend will be available at: http://localhost:8000/"
echo "✓ Admin panel at: http://localhost:8000/admin/"
echo ""

echo -e "${GREEN}TERMINAL 2: Admin Dashboard${NC}"
echo "Location: admin/"
echo "Command:"
echo "  cd admin"
echo "  npm run dev"
echo ""
echo "Expected Output:"
echo "  VITE v... ready in ... ms"
echo "  ➜  Local:   http://localhost:5173/"
echo ""
echo "✓ Admin will be available at: http://localhost:5173/"
echo "✓ Test login credentials:"
echo "  - Username: admin"
echo "  - Password: admin123"
echo ""

echo -e "${GREEN}TERMINAL 3: Public User App${NC}"
echo "Location: public user/"
echo "Command:"
echo "  cd \"public user\""
echo "  npm run dev"
echo ""
echo "Expected Output:"
echo "  VITE v... ready in ... ms"
echo "  ➜  Local:   http://localhost:5174/"
echo ""
echo "✓ Public app will be available at: http://localhost:5174/"
echo "✓ No login required for public app"
echo ""

echo -e "${YELLOW}===============================================${NC}"
echo -e "${YELLOW}After starting all 3 services:${NC}"
echo -e "${YELLOW}===============================================${NC}"
echo ""
echo "1. Open browser: http://localhost:5173"
echo "2. You'll see the login page"
echo "3. Login with:"
echo "   - Username: admin"
echo "   - Password: admin123"
echo "4. You should see the Dashboard with real data from database"
echo ""

echo -e "${YELLOW}Test Data Available:${NC}"
echo "  - 2 sample shelters (Agusan del Norte)"
echo "  - 5 earthquake records (Caraga region)"
echo "  - 5 safety tips"
echo "  - 6 coordinator accounts"
echo ""

echo -e "${YELLOW}Available Coordinator Accounts:${NC}"
echo "  1. username: admin, password: admin123 (Admin role)"
echo "  2. username: coordinator_butuan, password: coordinator_butuan123"
echo "  3. username: coordinator_agusan_norte, password: coordinator_agusan_norte123"
echo "  4. username: coordinator_surigao_sur, password: coordinator_surigao_sur123"
echo "  5. username: coordinator_agusan_sur, password: coordinator_agusan_sur123"
echo "  6. username: coordinator_cabadbaran, password: coordinator_cabadbaran123"
echo ""

echo -e "${YELLOW}Quick Links:${NC}"
echo "  Admin Dashboard: http://localhost:5173/"
echo "  Public User App: http://localhost:5174/"
echo "  API Documentation: http://localhost:8000/api/"
echo "  Django Admin Panel: http://localhost:8000/admin/"
echo "  API Shelters: http://localhost:8000/api/shelters/"
echo "  API Earthquakes: http://localhost:8000/api/earthquakes/"
echo "  API Alerts: http://localhost:8000/api/alerts/"
echo ""

echo -e "${BLUE}======================================${NC}"
echo -e "${BLUE}  Ready to Start! Open 3 Terminals   ${NC}"
echo -e "${BLUE}======================================${NC}"
echo ""
